from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from app.models import DispatchInterval


INTERVAL_HOURS = 0.25


class ReportUnavailableError(RuntimeError):
    pass


@dataclass(frozen=True)
class DispatchTableRow:
    timestamp: datetime
    solar_kw: float
    load_kw: float
    price_eur_per_kwh: float
    solar_to_load_kw: float
    battery_charge_kw: float
    battery_discharge_kw: float
    grid_import_kw: float
    curtailed_solar_kw: float
    soc_pct: float


@dataclass(frozen=True)
class WeeklyReport:
    grid_spend_with_battery_eur: float
    grid_spend_without_battery_eur: float
    savings_eur: float
    total_battery_charged_kwh: float
    total_battery_discharged_kwh: float
    total_solar_kwh: float
    curtailed_solar_kwh: float
    solar_self_consumption_pct: float
    labels: list[str]
    soc_pct_series: list[float]
    dispatch_rows: list[DispatchTableRow]


def get_weekly_report() -> WeeklyReport:
    """
    Build weekly report metrics from stored dispatch results.

    This service intentionally does not run dispatch. Dispatch is derived data and
    should be generated by the bootstrap/run_dispatch commands before viewing the
    report.
    """
    intervals = list(
        DispatchInterval.objects.select_related("point").order_by("point__timestamp")
    )

    if not intervals:
        raise ReportUnavailableError(
            "No dispatch rows found. Run `python manage.py bootstrap_demo --force --with-dispatch` first."
        )

    grid_spend_with_battery_eur = 0.0
    grid_spend_without_battery_eur = 0.0

    total_battery_charged_kwh = 0.0
    total_battery_discharged_kwh = 0.0
    total_solar_kwh = 0.0
    curtailed_solar_kwh = 0.0

    labels: list[str] = []
    soc_pct_series: list[float] = []
    dispatch_rows: list[DispatchTableRow] = []

    for interval in intervals:
        point = interval.point

        solar_kwh = point.solar_kw * INTERVAL_HOURS
        load_kwh = point.load_kw * INTERVAL_HOURS

        grid_import_with_battery_kwh = interval.grid_import_kw * INTERVAL_HOURS

        # Counterfactual: same PV and same load, but no battery.
        # PV still serves load first, no export is allowed, surplus PV is curtailed.
        grid_import_without_battery_kwh = max(0.0, load_kwh - solar_kwh)

        grid_spend_with_battery_eur += (
            grid_import_with_battery_kwh * point.grid_price_eur_per_kwh
        )
        grid_spend_without_battery_eur += (
            grid_import_without_battery_kwh * point.grid_price_eur_per_kwh
        )

        total_battery_charged_kwh += interval.battery_charge_kw * INTERVAL_HOURS
        total_battery_discharged_kwh += interval.battery_discharge_kw * INTERVAL_HOURS
        total_solar_kwh += solar_kwh
        curtailed_solar_kwh += interval.curtailed_solar_kw * INTERVAL_HOURS

        labels.append(point.timestamp.strftime("%a %H:%M"))
        soc_pct_series.append(round(interval.soc_pct, 2))

        dispatch_rows.append(
            DispatchTableRow(
                timestamp=point.timestamp,
                solar_kw=point.solar_kw,
                load_kw=point.load_kw,
                price_eur_per_kwh=point.grid_price_eur_per_kwh,
                solar_to_load_kw=interval.solar_to_load_kw,
                battery_charge_kw=interval.battery_charge_kw,
                battery_discharge_kw=interval.battery_discharge_kw,
                grid_import_kw=interval.grid_import_kw,
                curtailed_solar_kw=interval.curtailed_solar_kw,
                soc_pct=interval.soc_pct,
            )
        )

    solar_self_consumption_pct = (
        ((total_solar_kwh - curtailed_solar_kwh) / total_solar_kwh) * 100.0
        if total_solar_kwh > 0
        else 0.0
    )

    savings_eur = grid_spend_without_battery_eur - grid_spend_with_battery_eur

    return WeeklyReport(
        grid_spend_with_battery_eur=round(grid_spend_with_battery_eur, 2),
        grid_spend_without_battery_eur=round(grid_spend_without_battery_eur, 2),
        savings_eur=round(savings_eur, 2),
        total_battery_charged_kwh=round(total_battery_charged_kwh, 1),
        total_battery_discharged_kwh=round(total_battery_discharged_kwh, 1),
        total_solar_kwh=round(total_solar_kwh, 1),
        curtailed_solar_kwh=round(curtailed_solar_kwh, 1),
        solar_self_consumption_pct=round(solar_self_consumption_pct, 1),
        labels=labels,
        soc_pct_series=soc_pct_series,
        dispatch_rows=dispatch_rows,
    )