# Generated by Django 5.2.14 on 2026-05-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('solar_kw', models.FloatField()),
                ('load_kw', models.FloatField()),
                ('grid_price_eur_per_kwh', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DispatchInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_to_load_kw', models.FloatField()),
                ('battery_charge_kw', models.FloatField()),
                ('battery_discharge_kw', models.FloatField()),
                ('grid_import_kw', models.FloatField()),
                ('curtailed_solar_kw', models.FloatField()),
                ('soc_kwh', models.FloatField()),
                ('soc_pct', models.FloatField()),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='app.timeseriespoint')),
            ],
            options={
                'ordering': ['point__timestamp'],
            },
        ),
    ]
